services:
  postgres-db:
    image: postgres:15-alpine
    container_name: calisat-db-catalogo
    environment:
      POSTGRES_DB: calisat_catalogo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - calisat_catalogo_data:/var/lib/postgresql/data
    networks:
      - calisat-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calisat_catalogo"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calisat-ms-catalogo
    ports:
      - "8082:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - calisat-net

networks:
  calisat-net:
    driver: bridge

volumes:
  calisat_catalogo_data:
